name: Deploy da CMA Landing Page

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy da CMA Landing Page
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm ci

      - name: Build website
        run: pnpm run build

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0

        with:
          host: "ftp.cmadigitalmusic.com.br"
          user: "cmadigitalmusic1"
          password: ${{ secrets.CMA_PASSWORD }} 
          localDir: ".next" 
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com